[project]
name = "mod_poly"
dependencies = [
"maturin==1.1.0",
"tomli==2.0.1",
"numpy==1.24.1",
"tqdm==4.64.1"]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = ["pyo3"]